# Use root/example as user/password credentials
version: '3.1'

services:

  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432